### ISSUE TITLE
What to wait for after calling createHiddenService()

### ISSUE THREAD

**Issue by mattcollier** [Mowje/node-ths#3]
My code does this:
ths.createHiddenService('noxious','1111', true);
myAddress=ths.getOnionAddress('noxious');

An exception is generated on the second line because at that moment tor is doing a 'reload config' as per the node-ths documentation.

What trigger should I be looking for that tor is ready for business?  Should there be a callback function on createHiddenService()?

**Comment by abenmrad** [comment]
That's a problem indeed. ths doesn't expose any events yet. I have an idea about how to fix this; gonna work on it.

**Comment by abenmrad** [comment]
Fixed in v2.1.4 that I just [released](https://github.com/Mowje/node-ths/releases/tag/v2.1.4). Pushed it to npm as well. Tell me if something of that kind is what you wanted.

**Comment by mattcollier** [comment]
Thanks for the prompt response (and the module)!  Yes, you're on the right track.  Unfortunately, although I'm no longer getting an uncaught exception, when I do:

ths.createHiddenService('noxious','1111', true);
myAddress=ths.getOnionAddress('noxious', function(err, function() {...}));

The callback is never getting executed, however if the service already exists, the callback works properly.  If you want to see exactly what I'm doing, see: https://github.com/mattcollier/noxious/blob/master/nox-main.js#L159

**Comment by abenmrad** [comment]
This is weird, because I tried again the async version of the method in a context where the hidden service doesn't exist yet. See [this](https://github.com/Mowje/node-ths/blob/fe797439d90361dc449162ac91a52d3e43821006/example.js#L74).

Please be sure that the newly created service is saved (either by using parameter `applyNow` as `true` or calling `ths.saveConfig()`)
